server {
    listen 80;
    server_name notes.editors.one;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name notes.editors.one;

    ssl_certificate /etc/letsencrypt/live/notes.editors.one/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/notes.editors.one/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 50m;

    location = /yandex_0c6eee059be69a8f.html {
        root /var/www/static;
    }

    location = /0312fe9cfda74eccb1eb2772636338e5.txt {
        root /var/www/static;
    }

    location = /api/subscribe {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Content-Type $content_type;
    }

    location / {
        proxy_pass http://ghost-2:2368;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

server {
    listen 80 default_server;
    server_name _;

    client_max_body_size 50m;

    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location /staging/ {
        proxy_pass http://api-staging:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://ghost:2368;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
